DROP DATABASE IF EXISTS accounts;
CREATE DATABASE accounts;
\c accounts

CREATE TABLE IF NOT EXISTS bets (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    eventID VARCHAR(255) NOT NULL,
    period VARCHAR(50) NOT NULL,
    betType VARCHAR(50) NOT NULL,
    line DECIMAL(10,2),
    betAmount DECIMAL(10,2) NOT NULL,
    potentialWinnings DECIMAL(10,2) NOT NULL,
    date VARCHAR(255) NOT NULL,
    homeTeam VARCHAR(255) NOT NULL,
    awayTeam VARCHAR(255) NOT NULL,
    odds VARCHAR(255) NOT NULL,
    teamToWin VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending'
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    balance DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    stripe_session_id VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);